# Generated by Django 5.0.14 on 2025-11-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('escuela', 'Escuela'), ('cdi', 'CDI'), ('hogar', 'Hogar'), ('geriatrico', 'Geriátrico'), ('otro', 'Otro')], max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlatoObservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_plato', models.CharField(blank=True, choices=[('principal', 'Plato principal'), ('guarnicion', 'Guarnición'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('otro', 'Otro')], max_length=50, null=True)),
                ('porciones_servidas', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('energia_kcal_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proteinas_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('grasas_totales_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('carbohidratos_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fibra_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('sodio_mg_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Plato observado',
                'verbose_name_plural': 'Platos observados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngredientePlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad', models.CharField(default='g', max_length=20)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('energia_kcal', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('proteinas_g', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('grasas_totales_g', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('carbohidratos_g', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('fibra_g', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('sodio_mg', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes_en_platos', to='nutricion.alimentonutricional')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='auditoria.platoobservado')),
            ],
            options={
                'verbose_name': 'Ingrediente de plato',
                'verbose_name_plural': 'Ingredientes de plato',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisitaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena'), ('vianda', 'Vianda')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='auditoria.institucion')),
            ],
            options={
                'verbose_name': 'Visita de auditoría',
                'verbose_name_plural': 'Visitas de auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='auditoria.visitaauditoria'),
        ),
        migrations.AddIndex(
            model_name='visitaauditoria',
            index=models.Index(fields=['institucion', '-fecha'], name='auditoria_v_institu_4d9c5c_idx'),
        ),
    ]
