# Generated by Django 5.0.14 on 2025-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaauditoria',
            name='formulario_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitaauditoria',
            name='formulario_respuestas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
