# Generated by Django 5.0.14 on 2025-12-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_visitaauditoria_formulario_completado_and_more'),
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_plato', models.CharField(choices=[('principal', 'Plato principal'), ('guarnicion', 'Guarnición'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('energia_kcal_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proteinas_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('grasas_totales_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('carbohidratos_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fibra_g_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('sodio_mg_total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Plato plantilla',
                'verbose_name_plural': 'Platos plantilla',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IngredientePlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad', models.CharField(default='g', max_length=20)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutricion.alimentonutricional')),
                ('plato_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_plantilla', to='auditoria.platoplantilla')),
            ],
            options={
                'verbose_name': 'Ingrediente plantilla',
                'verbose_name_plural': 'Ingredientes plantilla',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
