# Generated by Django 5.0.14 on 2025-12-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_platoplantilla_ingredienteplantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienteplato',
            name='agua_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='calcio_mg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='fosforo_mg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='grasas_monoinsat_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='grasas_poliinsat_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='grasas_saturadas_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='hierro_mg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='potasio_mg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='vitamina_c_mg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ingredienteplato',
            name='zinc_mg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='agua_g_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='calcio_mg_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='fosforo_mg_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='grasas_monoinsat_g_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='grasas_poliinsat_g_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='grasas_saturadas_g_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='hierro_mg_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='potasio_mg_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='vitamina_c_mg_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platoobservado',
            name='zinc_mg_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
