# Generated by Django 5.0.14 on 2025-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_ingredienteplato_agua_g_ingredienteplato_calcio_mg_and_more'),
        ('nutricion', '0002_alimentonutricional_nutricion_a_nombre_672b80_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingredienteplantilla',
            index=models.Index(fields=['plato_plantilla', 'orden'], name='auditoria_i_plato_p_92feed_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredienteplato',
            index=models.Index(fields=['plato', 'orden'], name='auditoria_i_plato_i_5a4811_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredienteplato',
            index=models.Index(fields=['alimento'], name='auditoria_i_aliment_319bda_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['tipo', 'activo'], name='auditoria_i_tipo_844899_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['activo', 'nombre'], name='auditoria_i_activo_6d3dba_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['codigo'], name='auditoria_i_codigo_f6955a_idx'),
        ),
        migrations.AddIndex(
            model_name='institucion',
            index=models.Index(fields=['comuna', 'activo'], name='auditoria_i_comuna_80ddf0_idx'),
        ),
        migrations.AddIndex(
            model_name='platoobservado',
            index=models.Index(fields=['visita', 'tipo_plato'], name='auditoria_p_visita__6ae140_idx'),
        ),
        migrations.AddIndex(
            model_name='platoobservado',
            index=models.Index(fields=['visita'], name='auditoria_p_visita__4f4ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='platoplantilla',
            index=models.Index(fields=['tipo_plato', 'activo'], name='auditoria_p_tipo_pl_56949a_idx'),
        ),
        migrations.AddIndex(
            model_name='platoplantilla',
            index=models.Index(fields=['activo', 'nombre'], name='auditoria_p_activo_a38b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaauditoria',
            index=models.Index(fields=['-fecha'], name='auditoria_v_fecha_525dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaauditoria',
            index=models.Index(fields=['tipo_comida', '-fecha'], name='auditoria_v_tipo_co_15f5da_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaauditoria',
            index=models.Index(fields=['fecha'], name='auditoria_v_fecha_707a33_idx'),
        ),
    ]
