# Generated by Django 5.0.14 on 2025-11-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de alimento',
                'verbose_name_plural': 'Categorías de alimentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlimentoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_argenfood', models.IntegerField(unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('especie', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_base', models.CharField(default='100 g', max_length=20)),
                ('energia_kj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energia_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agua_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('proteinas_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('grasas_totales_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('carbohidratos_totales_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('carbohidratos_disponibles_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fibra_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cenizas_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sodio_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('potasio_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('calcio_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fosforo_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('hierro_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('zinc_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tiamina_mg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('riboflavina_mg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('niacina_mg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vitamina_c_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('grasas_saturadas_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('grasas_monoinsat_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('grasas_poliinsat_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('colesterol_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ag_c14_0_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ag_c16_0_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ag_c18_0_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ag_c18_1w9_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ag_c18_2w6_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ag_c18_3w3_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ag_epa_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ag_dha_g', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alimentos', to='nutricion.categoriaalimento')),
            ],
            options={
                'verbose_name': 'Alimento nutricional',
                'verbose_name_plural': 'Alimentos nutricionales',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['categoria', 'nombre'], name='nutricion_a_categor_c4134b_idx')],
            },
        ),
    ]
