# Generated by Django 5.0.14 on 2025-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alimentonutricional',
            index=models.Index(fields=['nombre'], name='nutricion_a_nombre_672b80_idx'),
        ),
        migrations.AddIndex(
            model_name='alimentonutricional',
            index=models.Index(fields=['codigo_argenfood'], name='nutricion_a_codigo__468771_idx'),
        ),
        migrations.AddIndex(
            model_name='alimentonutricional',
            index=models.Index(fields=['energia_kcal'], name='nutricion_a_energia_523405_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaalimento',
            index=models.Index(fields=['codigo'], name='nutricion_c_codigo_7ff87d_idx'),
        ),
    ]
